# Generated by Django 3.1.1 on 2020-09-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False, help_text='IMPORTANT: This item will not appear (even if you set "Go-live date/time") unless this checkbox is checked. This is to help prevent you from releasing it to the world before you are ready.', verbose_name='Is Live')),
                ('go_live_at', models.DateTimeField(blank=True, help_text="If set, this item will not go live until this date (assuming 'Is Live' is set).", null=True, verbose_name='Go-live date/time')),
                ('expire_at', models.DateTimeField(blank=True, help_text='If set, this item will stop being displayed after this date.', null=True, verbose_name='Expiry date/time')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, help_text="This field should rarely be touched. It will auto-populate the first time this item is saved withthe 'Is Live' checkbox checked. It's only editable to allow Admins to change this item's sort order.", null=True, verbose_name='First published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='Last published at')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['-first_published_at'],
            },
        ),
    ]
