# Generated by Django 3.1.1 on 2020-09-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0004_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False, help_text='IMPORTANT: This item will not appear (even if you set "Go-live date/time") unless this checkbox is checked. This is to help prevent you from releasing it to the world before you are ready.', verbose_name='Is Live')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
