# Generated by Django 3.1.1 on 2020-09-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_simplephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('live', models.BooleanField(default=False, verbose_name='Is Live')),
            ],
            options={
                'verbose_name': 'Simple Thing',
                'verbose_name_plural': 'Simple Thing',
            },
        ),
        migrations.AlterModelOptions(
            name='simplephoto',
            options={'verbose_name': 'Simple Photo', 'verbose_name_plural': 'Simple Photos'},
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Related Link',
                'verbose_name_plural': 'Related Link',
            },
        ),
    ]
